// Code generated by "stringer -type=JobResult"; DO NOT EDIT.

package queue

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fail-0]
	_ = x[Success-1]
	_ = x[Skip-2]
}

const _JobResult_name = "FailSuccessSkip"

var _JobResult_index = [...]uint8{0, 4, 11, 15}

func (i JobResult) String() string {
	if i >= JobResult(len(_JobResult_index)-1) {
		return "JobResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobResult_name[_JobResult_index[i]:_JobResult_index[i+1]]
}
